# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: build
  jobs:
    - job:
      steps:
      - task: DotNetCoreCLI@2
        displayName: Restore
        inputs:
          command: 'restore'
          projects: '**/MultiTenant.Core.csproj'

      - task: DotNetCoreCLI@2
        displayName: Build
        inputs:
          command: 'build'
          projects: '**/MultiTenant.Core.csproj'
          arguments: '-c Release'

      - task: NuGetCommand@2
        inputs:
          command: 'pack'
          packagesToPack: '**/MultiTenant.Core.csproj'
          versioningScheme: 'off'

